# Generated by Django 5.1.6 on 2025-02-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previewIMG', models.ImageField(upload_to='previewIMG')),
                ('previewTitle', models.CharField(max_length=100)),
                ('previewText', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleImg', models.ImageField(upload_to='')),
                ('titleText', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.blog')),
            ],
        ),
    ]
