# Generated by Django 5.1.6 on 2025-02-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcollect',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogcollect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.blogcollect'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='previewIMG',
            field=models.ImageField(upload_to='previewIMG/'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='titleImg',
            field=models.ImageField(upload_to='previewIMG/'),
        ),
    ]
