# Generated by Django 5.1.6 on 2025-02-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_getblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetBlog',
        ),
    ]
