# Generated by Django 5.1.6 on 2025-02-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blogcollect_slug_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcollect',
            name='previewIMG',
            field=models.ImageField(null=True, upload_to='previewIMG/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogcollect',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
