# Generated by Django 5.1.6 on 2025-03-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
