# Generated by Django 5.1.6 on 2025-03-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='available',
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog'),
        ),
    ]
