# Generated by Django 5.1.6 on 2025-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_blog_author_blog_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='available',
            field=models.BooleanField(default=True, verbose_name=' - Публично'),
        ),
    ]
