# Generated by Django 5.1.6 on 2025-03-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_blog_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blogcollect',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogCollect',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
